### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [Edgardo21/PHP-TipCalculator#1]
Thanks for submitting your pre-work, but could you make some changes to your readme? Can you please review the section in the pre-work about [the README](https://github.com/codepath/university_courses_content/blob/master/web_security_university/snippets/prework.md#3-submit-your-code-for-review) for your project? 

In particular, be sure to start from the README template that is linked there, check off your completed required and optional features (`[x]`), list any additional features, and [include a recorded app walkthrough with LiceCap](http://www.cockos.com/licecap/). 

Please re-submit your project on your [application dashboard](https://apply.codepath.com/dashboard/), and it will notify us to review again.

**Comment by Edgardo21** [comment]
my .gif has the complete walkthrough with licecap already
